services:
  frontend:
    build:
      context: ./linktree
      dockerfile: Dockerfile
    container_name: linktree-frontend
    restart: unless-stopped
    networks:
      - slouowze-dot-fr

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: linktree-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    networks:
      - slouowze-dot-fr

networks:
  slouowze-dot-fr:
    external: true
